export const dom = {
  blocksElement: document.querySelector("#blocks"),
  levelTitle: document.querySelector("#level-title"),
  levelCount: document.querySelector("#level-count"),
  levelNote: document.querySelector("#level-note"),
  levelSelector: document.querySelector("#level-selector"),
  goal: document.querySelector("#goal"),
  unknown: document.querySelector("#unknown"),
  result: document.querySelector("#result"),
  ruleLabel: document.querySelector("#rule-label"),
  stepExplanation: document.querySelector("#step-explanation"),
  hintText: document.querySelector("#hint-text"),
  proofLog: document.querySelector("#proof-log"),
  proofLogTab: document.querySelector("#proof-log-tab"),
  levelsTab: document.querySelector("#levels-tab"),
  proofLogPanel: document.querySelector("#proof-log-panel"),
  levelsPanel: document.querySelector("#levels-panel"),
  openLevelsButton: document.querySelector("#open-levels-button"),
  resetButton: document.querySelector("#reset-button"),
  hintButton: document.querySelector("#hint-button"),
  nextButton: document.querySelector("#next-button"),
  soundToggle: document.querySelector("#sound-toggle"),
};
